### ISSUE TITLE
Support deprecated input values

### ISSUE THREAD

**Issue by jhalborg** [dimaMachina/graphql-eslint#2415] opened 2024-06-24 07:17 UTC
**Is your feature request related to a problem? Please describe.**

If the schema deprecates input values (args, input fields) the linter will complain with the error

`Parsing error: [graphql-eslint] Error while loading schema: Directive "@deprecated" may not be used on INPUT_FIELD_DEFINITION.`

**Describe the solution you'd like**

No error, as deprecated [input values are allowed in GraphQL](https://github.com/graphql/graphql-spec/pull/805)

**Describe alternatives you've considered**

--

**Additional context**

`"@graphql-eslint/eslint-plugin": "^3.20.1",`

Schema sample:

```graphql
type Query {
  controlStates(id: ID!, Hierarchy: Hierarchy @deprecated(reason: "No longer required, info is retrieved based on device id")): Device
}
```

**Comment by dimaMachina** [comment] 2024-06-24 09:36
https://github.com/dimaMachina/graphql-eslint/issues/1891#issuecomment-1734533636

**Comment by jhalborg** [comment] 2024-07-11 14:08
Hehe, deja vu 😄 Sorry I missed your replies last year. 

`"graphql": "16.8.1",`

**Comment by dimaMachina** [comment] 2024-11-24 12:44
I can't reproduce your error, please provide runnable reproduction, I am closing your issue for now

**Closed by dimaMachina** 2024-11-24 12:44 UTC
